name: Manually triggered workflow 2
on:
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.qqq }}!"
          echo "- in ${{ github.event.inputs.qqq }}!"
